### ISSUE TITLE
Wallet Bridge

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/adapter#425]
Client:

- [x] create common JS wallet client API #423, #424
- [x] wallet preference  #434 #423 #439 
- [x] publish wallet JS client API #426
- [ ] tests

Server:

- [x] wallet bridge API in rp & issuer #413, #417, #418
- [x] save wallet preferences

TODOs

- [ ] rp OIDC / userinfo to save user wallet preference

**Comment by sudeshrshetty** [comment]
WACI implementation is going to replace this, closing this issue.
