### ISSUE TITLE
[epic-adapter] WACI Issuance flow using DIDComm v2 + Credential Manifest

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/adapter#545]
- [x] [Support to configure WACI during issuer profile creation](https://github.com/trustbloc/adapter/issues/546)
- [x] [Generate OOB Message](https://github.com/trustbloc/adapter/issues/553)
- [x] [Handle Issue Credential - Propose Credential Message](https://github.com/trustbloc/adapter/issues/554)
- [x] [Handle Issue Credential - Request Credential Message](https://github.com/trustbloc/adapter/issues/555)
- [x] [QR code support](https://github.com/trustbloc/adapter/issues/556)
- [x] #561 
- [x] #564 
- [x] https://github.com/trustbloc/adapter/issues/595
- [x] https://github.com/trustbloc/adapter/issues/563
- [x] https://github.com/trustbloc/adapter/issues/580
- [x] https://github.com/trustbloc/adapter/issues/562
- [x] https://github.com/trustbloc/adapter/issues/612

Reference - https://identity.foundation/waci-presentation-exchange/#issuance-2
